<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Rakeshs-MacBook-Air.local" failures="2" tests="2" name="Default test(failed)" time="0.025" errors="0" timestamp="2025-04-07T14:10:40 IST">
  <testcase classname="FailedTestRetryLogic.TestCaseExamples" name="testCase4" time="0.005">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
at FailedTestRetryLogic.TestCaseExamples.testCase4(TestCaseExamples.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testCase4 -->
  <testcase classname="FailedTestRetryLogic.TestCaseExamples" name="testCase3" time="0.001">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
at FailedTestRetryLogic.TestCaseExamples.testCase3(TestCaseExamples.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testCase3 -->
  <testcase classname="FailedTestRetryLogic.TestCaseExamples" name="testCase2" time="0.0">
    <ignored/>
  </testcase> <!-- testCase2 -->
  <testcase classname="FailedTestRetryLogic.TestCaseExamples" name="testCase1" time="0.0">
    <ignored/>
  </testcase> <!-- testCase1 -->
</testsuite> <!-- Default test(failed) -->
